### PR TITLE
Allow floats

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: nstarman <nstarkman@protonmail.com>

## Description

Allow float inputs to redshift-dependent methods.

## PR Checklist

- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by nstarman** [comment]
I think this covers all the inputs.

**Comment by ntessore** [comment]
I wonder if it's worth adding an abstraction layer to our input type definition here.  We could add a new `ArrayLike` generic alias that is only `float | ArrayT` for the time being, but can be expanded later without having to change all function signatures.

```py
ArrayLike = Union[float | ArrayT]

...

    def scale_factor(self, z: ArrayLike[ArrayT], /) -> ArrayT:
        ...
```

**Comment by ntessore** [comment]
Thinking about this more, we could even target PEP 696 and define:

```py
ArrayT = TypeVar('ArrayT', bound=Array)
ArrayLikeT = TypeVar('ArrayLikeT', default=float | ArrayT)

class Cosmology(Generic[ArrayT, ArrayLikeT], Protocol): ...
```

Cosmologies using numpy arrays could then accept `numpy.typing.ArrayLike` inputs, and e.g. `cosmo.comoving_distance([z1, z2])` would remain legal, which is a big plus in my mind.

**Comment by nstarman** [comment]
I agree it may be worth expanding the Generic type to be `float | Array`. I want to add mypy tests to the test suite to confirm this.
However this will not enable lists as inputs because they are neither float nor Array. I agree lists are convenient, but they are very different structures from a numerical library's Array. Permitting lists means Cosmology libraries would have to process all input!

**Comment by ntessore** [comment]
> However this will not enable lists as inputs because they are neither float nor Array.

Yes, that's exactly the intention. The *default* behaviour is to have `ArrayLike` be floats and arrays, which are always supported. But if a cosmology accepts e.g. all numpy `array_like` input, which includes sequences of floats, then it can set the `ArrayLikeT` to something more permissive than `float | Array`, like the full `np.typing.ArrayLike`.

**Comment by nstarman** [comment]
I see. Sorry for the confusion. Yes, this would be a good addition when that PEP is rolled out! Nitpicking a second here, but I think we'd need to make the Cosmology be 

```
class Cosmology(Protocol[InputType=ArrayLike, Array]):
```

So that inputs to functions can be changed as you said, but output types remain Array. This can be supported by variations generics.
I think all these extensions are great but also future work that can wait until after the first version.

**Review by ntessore — APPROVED** [review]

**Comment by ntessore** [comment]
Fair enough. I am just a little wary of restricting functionality that currently is universally supported.

**Comment by nstarman** [comment]
We might be able to support it now by going for a variadic generic implementation. This requires a Mypy plugin, which might be quite simple. I'll take a look.

**Comment by ntessore** [comment]
> We might be able to support it now by going for a variadic generic implementation. This requires a Mypy plugin, which might be quite simple. I'll take a look.

This already works right now if you use `TypeVar` from [`typing_extensions`](https://github.com/python/typing_extensions) to gain the `default=` parameter. We don't need variadic generics, the `ArrayLikeT` will use its default if not given:

```py
from typing_extensions import TypeVar

ArrayT = TypeVar('ArrayT', bound=Array)
ArrayLikeT = TypeVar('ArrayLikeT', default=float | ArrayT)

class Cosmology(Generic[ArrayT, ArrayLikeT], Protocol): ...

reveal_type(Cosmology[Array])  # Cosmology[Array, float | Array]
```

**Comment by nstarman** [comment]
I did a quick experiment using the typing_extensions `TypeVar` but I can't get mypy to recognize it as a `TypeVar`. I don't think it's supported yet. So we'll have to wait a bit for a default this way. I think we can still accomplish this with variadic generics and a mypy plugin. I'll take a closer look.

**Comment by ntessore** [comment]
Ok cool. It works well with pyright so I assumed mypy would be the same. We can also leave this for now if it's blocking.

**Comment by nstarman** [comment]
Pyright has a faster release exhedule. I do think this is a blocker for just floats, which we do want to support. I'll make a reminder issue to return to this, because it's definitely a valuable addition.

**Comment by nstarman** [comment]
I added a short table to the docs on which array libraries allow the addition of an array and a float.

**Comment by nstarman** [comment]
The review got dismissed because I pushed to the branch. The branch protection rules are set up so that an approval only applies to the most recent version of the PR.

**Pull request merged**
