### PR TITLE
Rename FLRW to HasDistanceFunctions

### PR DESCRIPTION
**Pull request by nstarman**
TODO:

 Some methods need to be broken out.

- [x] move `Otot0` (will also be renamed to `Omega_tot0`)
- [x] move `critical_density0`?
- [x] move `Otot`
- [x] move critical_density?

Also:

- [x] rename to `HasDistanceMeasures` ?

## PR Checklist

- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by nstarman** [comment]
@ntessore, where do you think we should move the non-distance measure attributes/methods.

**Comment by nstarman** [comment]
I'm hesitant to put anything on ``Cosmology``.
Maybe ``Omega_tot`` can go to something called ``HasComponents`` that all the ``Has<X>Component`` would subclass.
Not sure yet about the others.

**Comment by ntessore** [comment]
I think one more doesn't hurt, `HasCriticalDensity`? That's actually one of the lesser supported, so we will get some use out of that `isinstance` check.

**Comment by nstarman** [comment]
Done. Also, I folded `HasTcmb` into the distance measures.

**Review by ntessore — APPROVED** [review]
Starting to look finished. I think we could stick all of the `HasX` protocols into a single module (even just `_components`) if that made future classification easier (is that a component? distance-related? extra? see Tcmb) but that's an infinitesimal change.

**Comment by nstarman** [comment]
> Starting to look finished. 

Agreed! I think we need some documentation and a meeting to go over everything and make sure we're happy with v0.1.

> I think we could stick all of the `HasX` protocols into a single module (even just `_components`) if that made future classification easier (is that a component? distance-related? extra? see Tcmb) but that's an infinitesimal change.

I agree `_extra` is a bad categorization, and stuff should be re-arranged. Thankfully, the module location is private (all the Protocols should be accessed from ``cosmology.api`` or ``cosmology.api.compat``) and we are free to re-arrange to whatever makes the most internal sense, even after v0.1.
My thought is whether we should public scope ``cosmology.api.components``, and move all the `HasXComponents`
from ``cosmology.api.__all__`` to ``cosmology.api.compnents.__all__``. Also, I think we should rename the ``compat``
module to ``compat`` since, though the classes are used for the compat modules, these are really wrappers and can be used more generally.

**Comment by nstarman** [comment]
I forgot to add `HasTotalComponent` to the top module. I'll import it and then merge.

**Pull request merged**
