### PR TITLE
Making Cosmology generic wrt the method input type.

### PR DESCRIPTION
**Pull request by nstarman**
Part 2 of #28. 
PEP 696 is not out yet, so we have to wait on that.

## PR Checklist

- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by ntessore** [comment]
Do you want to depend on typing-extensions to get this working right away?

**Comment by nstarman** [comment]
Unfortunately, I don't think `mypy` is compatible with the `typing_extensions` version of `TypeVar`.

**Comment by ntessore** [comment]
True, but there is an open issue for mypy with two associated PRs, and it works already with pyright, so it's a considerably shorter wait than PEP 696.

**Comment by nstarman** [comment]
I think after this PR we only need to write some docs and then we're good to release v0.1!

**Comment by nstarman** [comment]
@ntessore, are you fine to merge this? When PEP 696 is out the 2nd type will be optional, but is required for now.

**Comment by nstarman** [comment]
Having updated the Astropy wrapper, I do think this added feature should be included in v0.1. When the PEP is adopted by mypy we can make the 2nd type optional.

**Comment by ntessore** [comment]
Looks good to me. Do we actually ever need non-variant `ArrayT` and `InputT`? If not, can we make those variant and get rid of the slightly ugly `_co`/`_contra` suffixes?

**Comment by nstarman** [comment]
I also don't particularly like the `_co`, `_contra` suffix, but they are pretty standard for indicating the structure of the type. Thankfully https://peps.python.org/pep-0695/#variance-inference and related PEP will eventually remove the need to specify the type variance and will make this much prettier.

**Review by ntessore — APPROVED** [review]

**Pull request merged**
