### PR TITLE
background hierarchy

### PR DESCRIPTION
**Pull request by nstarman**
See https://github.com/orgs/cosmology-api/discussions/1

## PR Checklist

- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by ntessore** [comment]
I'm not sure I understand this class hierarchy. To have methods as functions of redshift only, you necessarily need to have an isotropic cosmology. The `HomogeneousBackground` class must forever be empty in order to not break the interface, so it is pointless to ever test for it, and it's also pointless to ever test for `HomogeneousIsotropicBackground`, since `IsotropicBackground` is always enough. So the hierarchy could be reduced to `Background` and `IsotropicBackground`.  In `Background`, the `scale_factor0` should be moved to `IsotropicBackground`, which means `Background` is essentially empty as well. So we might as well have `Isotropic` as the only remaining class.

I think it might really be the case that going back to `FLRW` is the best choice.

**Comment by ntessore** [comment]
How about this perspective: For the API, we do not really care about the physical meaning of the cosmology, we only care about the interface. In the sense of: any cosmology that has distance functions of redshift is fine to use in place of e.g. the astropy ones.

So why don't we say that `BackgroundCosmology` (maybe with a name that makes it clearer) is any cosmology which has distance functions of redshift only?

**Comment by nstarman** [comment]
Following our meeting, I've eliminate the hierarchy.
One thing I'm not sure about is the name ``FLRWBackground`` versus ``BackgroundFLRW``. I think I'm more inclined toward the latter as it keeps, e.g. ``BackgroundBianchi`` grouped with the other Backgrounds.

**Comment by nstarman** [comment]
So ``FLRW`` by itself is not a great name as all-caps names are meant to be [constants](https://peps.python.org/pep-0008/#constants). ``FriedmannLemaitreRobertsonWalker`` is more verbose, but also better. Users of the API are free to import as ``from cosmology.api import FriedmannLemaitreRobertsonWalker as FLRW`` if they don't want to follow PEP8.

**Comment by nstarman** [comment]
@ntessore. ready for final review.

**Comment by nstarman** [comment]
This PR should be merged before the others.

**Review by ntessore — APPROVED** [review]
LGTM. I take it that the `BackgroundCosmologyWrapperAPI` is no longer a thing because we have `CosmologyWrapperAPI` and the components.

**Pull request merged**
